import setuptools

setuptools.setup(
    name="fastapi",
    version="0.54.1a0",
    author="Sebastián Ramírez",
    author_email="tiangolo@gmail.com",
    description="FastAPI framework, high performance, easy to learn, fast to code, ready for production",
    long_description="""FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.6+ based on standard Python type hints.""",
    long_description_content_type="text/markdown",
    url="https://github.com/threfo/fastapi",
    packages=setuptools.find_packages(),
    install_requires=[
        "starlette ==0.13.2",
        "pydantic >=0.32.2,<2.0.0",
        "requests",
        "aiofiles",
        "jinja2",
        "python-multipart",
        "itsdangerous",
        "pyyaml",
        "graphene",
        "ujson",
        "orjson",
        "email_validator",
        "uvicorn",
        "async_exit_stack",
        "async_generator"
    ],
    classifiers=[
        "Intended Audience :: Information Technology",
        "Intended Audience :: System Administrators",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python",
        "Topic :: Internet",
        "Topic :: Software Development :: Libraries :: Application Frameworks",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development",
        "Typing :: Typed",
        "Development Status :: 4 - Beta",
        "Environment :: Web Environment",
        "Framework :: AsyncIO",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
        "Topic :: Internet :: WWW/HTTP",
    ]
)
